"""Visualization for test data, generated by ./conftest.py fixtures (not actual tests)

"""
import numpy as np
import numpy.typing as npt
import pytest
from . import conftest  # Imported by pytest anyway
from terrain_ridges import build_edges, topo_graph
from terrain_ridges.topo_graph import T_Graph, T_IndexArray, T_MaskArray


# Skip the whole module with "not visualize" marker (default)
pytestmark = pytest.mark.visualize

@pytest.fixture
def plotly_go(request):
    """Plotly fixture, skip if not installed"""
    return pytest.importorskip('plotly.graph_objects')

# Slice axis to project 3D grids in 2D plane
SLICE_AXIS = 0      #TODO: Change this
SLICE_LABEL = 'xyz'[SLICE_AXIS]

#
# Altitude visualization
#
def test_altitude_grid(plotly_go, altitude_grid):
    """Visualize various altitude grids (not actual test)

    [Hint] visualization one-liner:
    - 2D: `go.Figure(data=go.Surface(z=altitude_grid)).show()`
    - 3D: `go.Figure(data=go.Surface(z=altitude_grid[:, :, <idx>])).show()`,
      where `:,:,<idx>` is a 2D slice of the data to be visualized
    """
    go = plotly_go
    fig = go.Figure(layout_title_text=f'Elevation grid, shape {altitude_grid.shape}')
    if altitude_grid.ndim == 1:
        fig.add_trace(go.Scatter(y=altitude_grid))
    elif altitude_grid.ndim == 2:
        fig.add_trace(go.Surface(z=altitude_grid))
    elif altitude_grid.ndim == 3:
        # Slice on axis
        index_exp: list[slice|int] = [np.s_[:]] * altitude_grid.ndim
        steps = []
        for idx in range(altitude_grid.shape[SLICE_AXIS]):
            index_exp[SLICE_AXIS] = idx
            fig.add_trace(go.Surface(z=altitude_grid[*index_exp], visible=idx==0))
            visible = np.arange(altitude_grid.shape[SLICE_AXIS]) == idx
            steps.append(dict(method='restyle', args=[{'visible': visible}], label=f'{SLICE_LABEL}={idx}'))
        fig.update_layout(sliders=[dict(steps=steps)])
    fig.show()

#
# Edge visualization
#
def adjust_node_points(points, mask: T_MaskArray, scale: float=.05) -> npt.NDArray[np.floating]:
    """Pull back edge's target nodes by 5% (to NOT overlap actual target-node)"""
    assert mask.shape[0] == 2 and points[0].shape == mask.shape, 'Point vs. target-mask shape mismatch'
    points = points.astype(float)
    points[:, mask] = points[:, mask] * (1-scale) + points[:, ::-1][:, mask] * scale
    return points

def visualize_edge_list(go, edge_list: T_IndexArray, altitude_grid: npt.NDArray|None, *,
                        edge_src_mask: T_MaskArray|None=None, title: str) -> None:
    """Visualize edge list"""
    title += f' - edges: {edge_list.shape[2:]}'
    points = edge_list

    # Handle scenarios with and w/o altitude
    if altitude_grid is None:
        alts = None
        # 1D case: same x and y values
        if points.shape[0] == 1:
            points = np.concatenate((points, points), axis=0)
    else:
        title += f', grid: {altitude_grid.shape}'
        alts = altitude_grid[*points]
        # Add altitude as next axis (if dimensions allow)
        if points.shape[0] < 3:
            points = np.concatenate((points, alts[np.newaxis]), axis=0)

    # Pull back edge-target a bit (to NOT overlap actual target-node)
    if edge_src_mask is None:   # Default to first edge-node is the source
        edge_src_mask = np.broadcast_to(([True], [False]), points[0].shape)
    points = adjust_node_points(points, ~edge_src_mask)
    # Separate individual edges with NaN-s (pad the second dimension)
    pad_width = [(0,0)] * points.ndim
    pad_width[1] = (0,1)
    points = np.pad(points, pad_width, constant_values=np.nan)

    # Combine  plotly.graph_objects.Scatter arguments
    # Convert coordinates to x=<arr>, y=<arr>, ... format
    kwargs = {k: v.T.flat for k, v in zip('xyz', points)}
    # Generate text and symbols for each marker
    text = np.indices(points.shape[1:]).astype(str)
    kwargs['text'] = ('edge:' + text[1] + '-' + text[0]).T.flat
    kwargs['mode'] = 'lines+markers'
    # Symbols denote source/target node
    symbols = np.where(edge_src_mask, 'circle', 'circle-open')
    symbols = np.pad(symbols, pad_width[1], constant_values='x')
    symbols = symbols.T.flat
    kwargs['marker_symbol'] = symbols
    # Color markers by node-altitude
    if alts is not None:
        kwargs['marker_color'] = np.pad(alts, pad_width[1:]).T.flat
        kwargs['marker_colorscale'] = 'viridis'

    fig = go.Figure(layout_title_text=title)
    fig.add_trace(go.Scatter3d(**kwargs) if 'z' in kwargs else go.Scatter(**kwargs))
    fig.show()

def visualize_graph(go, tgt_nodes: T_Graph, altitude_grid: npt.NDArray|None, *,
                    title: str='Graph', edge_dup: bool=False) -> None:
    """Visualize tree-graph (convert to edge list)"""
    grid_shape = tgt_nodes.shape[1:]
    # Skip edges, where target and source nodes are the same
    mask = (tgt_nodes != np.indices(grid_shape)).any(0)
    edge_list = np.stack((np.nonzero(mask), tgt_nodes[:, mask]), axis=1)
    edge_src_mask = None

    # Skip edge duplicates
    if not edge_dup:
        # Detect edges, where target of target is the source node
        dup_mask = (tgt_nodes[:, *tgt_nodes] == np.indices(grid_shape)).all(0)
        dup_mask = dup_mask[*edge_list].all(0)
        # Keep just one of these (arbitrary rule - smaller raveled node-index)
        dup_idx = np.ravel_multi_index(tuple(edge_list[:, :, dup_mask]), grid_shape).astype(int)
        mask = dup_mask.copy()
        mask[mask] = dup_idx[0] > dup_idx[1]
        dup_mask = dup_mask[~mask]
        edge_list = edge_list[:, :, ~mask]
        edge_src_mask = np.broadcast_to(([True], [False]), edge_list[0].shape).copy()
        edge_src_mask[1, dup_mask] = True

    visualize_edge_list(go, edge_list, altitude_grid, edge_src_mask=edge_src_mask, title=title)

def test_build_edge_list(plotly_go, altitude_grid):
    """Visualize initial edge list (not actual test)"""
    edge_list, lexsort_keys = build_edges.build_edge_list(altitude_grid)
    visualize_edge_list(plotly_go, edge_list, altitude_grid, title='Main edges')

def test_select_edges(plotly_go, altitude_grid):
    """Visualize edge-selection from the initial edge list"""
    edge_list, _ = build_edges.build_edge_list(altitude_grid)
    #TODO: select_edges() need "raveled" indices (mey need to change this later)
    edge_list_r = np.ravel_multi_index(tuple(edge_list), altitude_grid.shape).astype(int)
    edge_src_mask = topo_graph.select_edges(edge_list_r)
    mask = edge_src_mask.any(0)
    visualize_edge_list(plotly_go, edge_list[..., mask], altitude_grid,
                        edge_src_mask=edge_src_mask[..., mask], title='Selected edges')

def test_edge_list_to_graph(plotly_go, altitude_grid):
    """Visualize tree-graph created from initial edge list"""
    edge_list, _ = build_edges.build_edge_list(altitude_grid)
    #TODO: select_edges() need "raveled" indices (mey need to change this later)
    edge_list_r = np.ravel_multi_index(tuple(edge_list), altitude_grid.shape).astype(int)
    edge_src_mask = topo_graph.select_edges(edge_list_r)
    tgt_nodes = topo_graph.edge_list_to_graph(edge_list_r, edge_src_mask)
    # Unravel node indices, same as reshape graph
    tgt_nodes = topo_graph.reshape_graph(tgt_nodes, altitude_grid.shape)
    visualize_graph(plotly_go, tgt_nodes, altitude_grid, title='Graph')
