name: Validate ridge generator

on:
  push:
    branches: [ master, '**-test' ]
  pull_request:

env:
  SRC_URL: "https://www.iea-software.com/ftp/Emeraldv6/Geography/Eurasia/Elevations/SRTM3/N39E021.hgt.zip"

jobs:
  validate:
    runs-on: windows-latest

    env:
      SRC_DEM_DIR: "test/DEM"
      DEM_EXTENSIONS: ".dem, .hgt, .tif, .tiff"

    defaults:
      run:
        shell: pwsh

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Set up GDAL
      uses: trundev/setup-gdal@main
      id: setup-gdal
      with:
        rebuild-cache: ${{ github.event.inputs.REBUILD_CACHE }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install module
      run: python -m pip install --upgrade pip .[dev]

    - name: Download source DEM
      id: download-dem
      uses: ./.github/download-data
      with:
        source-urls: ${{ env.SRC_URL }}
        unpack-sources: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        UNPACK_DIR: ${{ env.SRC_DEM_DIR }}
        UNPACK_EXTENSIONS: ${{ env.DEM_EXTENSIONS }}

    - name: Run PyTest
      env:
        SRC_DEM: ${{ steps.download-dem.outputs.download-paths }}
      run: pytest -v --capture=tee-sys --ignore=GDAL~
